name: "Test workflow"
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '.github/*.yml'

jobs:
  test1:
    name: Test1
    permissions:
      contents: read
    if: |
      ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo 'Test1 ran'

  test2:
   name: Test2
   permissions:
     contents: read
   if: github.ref_name == 'main'
   runs-on: ubuntu-latest
   steps:
     - shell: bash
       run: |
         echo 'Test2 ran'


  test3:
   name: Test3
   permissions:
     contents: read
   runs-on: ubuntu-latest
   steps:
     - shell: bash
       run: |
         echo "Test3: ran on $NAME"
       env:
         NAME: "${{ github.ref_name }}"

  test4:
    name: Test4
    permissions:
      contents: read
    if: |
      ${{ github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo 'Test4 ran'


